### ISSUE TITLE
Code Execution

### ISSUE THREAD

**Issue by harshad018** [google-gemini/generative-ai-dart#204]
### Description of the feature request:

Get the code execution as soon as possible to the release on pub.dev, i have seen changes made for the code execution , but still not being released as v0.4.5 on pub.dev , please release that so that we can use it as soon as possible

### What problem are you trying to solve with this feature?

The generated code by gemini api will get tested at that time only , which will be a huge step forward since no ai right now have this code execution capacity , which makes this ai very much unique and integrating this with flutter will get this functionality on each and every device app built using gemini api.

### Any other information you'd like to share?

I am building my app which will have this specific functionality and i have to do it today only, i.e 10 aug 2024 SO PLEASE RELEASE THE LATEST DEPENDENCY AS SOON AS POSSIBLE.

**Comment by depombo** [comment]
Probably not advisable for production, but you can start testing it by doing the following in your `pubspec.yaml`
```yaml
  google_generative_ai:
    git:
      url: https://github.com/google-gemini/generative-ai-dart.git
      ref: main
      path: pkgs/google_generative_ai
```
